apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 3000 # Port yang akan diekspos oleh Service di dalam klaster Kubernetes
      targetPort: 3000 # Port yang digunakan oleh kontainer API Gateway (sesuai containerPort di Deployment)
      nodePort: 30000
  type: NodePort