apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30003
  type: NodePort