apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: luviandsp/auth-service:v1 # Ganti dengan image Docker Auth Service Anda
          ports:
            - containerPort: 3003