apiVersion: v1
kind: Service
metadata:
  name: chef-service
spec:
  selector:
    app: chef-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002
  type: NodePort