apiVersion: v1
kind: Service
metadata:
  name: frontend-jawa-restaurant
spec:
  selector:
    app: frontend-jawa-restaurant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer