apiVersion: v1
kind: Service
metadata:
  name: iot-service
spec:
  selector:
    app: iot-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
      nodePort: 30004
  type: NodePort