apiVersion: v1
kind: Service
metadata:
  name: waiter-service
spec:
  selector:
    app: waiter-service
  ports:
    - protocol: TCP
      port: 3001 # Port yang akan diekspos oleh Service
      targetPort: 3001 # Port yang digunakan oleh kontainer Waiter Service
      nodePort: 30001
  type: NodePort